/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/stn.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.SphereAction.play()
    actions.ConeAction.play()
    actions.CubeAction.play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Cube"
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[0, 1.6, 0]}
      />
      <mesh
        name="Sphere"
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials['Material.002']}
        position={[-2.39, 1.63, 0]}
      />
      <mesh
        name="Cone"
        castShadow
        receiveShadow
        geometry={nodes.Cone.geometry}
        material={materials['Material.001']}
        position={[2.42, 1.64, -0.03]}
      />
    </group>
  )
}

useGLTF.preload('/stn.gltf')
