/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef , useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/triangle.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.TriangleAction.play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Triangle"
        geometry={nodes.Triangle.geometry}
        material={materials.Triangle}
        position={[0, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/triangle.glb')